name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa 20.51.207.28 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -v azureuser@20.51.207.28 "echo 'SSH connection successful!'"

      - name: Deploy to VPS
        run: |
          scp -r ./build azureuser@20.51.207.28:/var/www/apache-react.bimash.com.np/
          ssh azureuser@20.51.207.28 "sudo systemctl restart apache2"
