name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 20.51.207.28 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -vvv azureuser@20.51.207.28 "echo 'SSH connection successful!'"

      - name: Deploy to Azure
        run: |
          scp -r ./dist azureuser@20.51.207.28:/var/www/apache-react.bimash.com.np/
          ssh azureuser@20.51.207.28 "sudo systemctl restart apache2"
