name: 🚀 Deploy frontend on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: 🔨 Install Packages and Build
        run: |
          npm install
          npm run build

      - name: 📂 Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd apache/apache-react/
            pnpm install
            pnpm build
            sudo rm -rf /var/www/apache-react.bimash.com.np/
            sudo mkdir -p /var/www/apache-react.bimash.com.np/
            sudo mv apache/apache-react/dist/* /var/www/apache-react.bimash.com.np

          # Copy files from the github dist folder to the server
